services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "0:3000"
    environment:
      NODE_ENV: production
    restart: always
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

networks:
  default:
